"""empty message

Revision ID: 3e5ec4fc3ba8
Revises: 6145015a8bfc
Create Date: 2021-11-02 14:36:51.162724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5ec4fc3ba8'
down_revision = '6145015a8bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caught_pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caught_pokemon')
    # ### end Alembic commands ###
